import React from "react";
import Head from "next/head";

export default function MembershipDetails() {
  return (
    <>
      <Head>
        <title>Fitt AF</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous"
        />
      </Head>
      <div class="signupBg">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-6 ">
              <h1 class="signupHeading">Membership Details</h1>
              <p>
                Purchase a membership with Fitt AF to receive an online personal
                training service that includes:
              </p>
              <ul>
                <li>
                  Initial phone consultation with Frankie or Alex to understand
                  your goals.
                </li>
                <li>
                  Personal training & nutrition plans created uniquely for you.
                </li>
                <li>Regular check-ins with your personal trainer.</li>
                <li>
                  Access to the Fitt AF app, which allows you to track workouts,
                  nutrition, programs and more.
                </li>
                <li>
                  Live workout advice and motivation through our app's chat
                  function.
                </li>
                <li>
                  Access to online video content including excersise
                  demonstrations and other fitness related content.
                </li>
                <li>
                  Become a part of the private members Fit AF facebook community
                  to find likeminded people.
                </li>
              </ul>

              <a href="/start">
                <button class="btn grow light" type="button" name="button">
                  Buy Membership
                </button>
              </a>
            </div>

            <div class="col-md-6 my-auto imgDiv">
              <img
                src="/images/home/app-icons.png"
                class="graphic"
                alt="Graphic showing the online personal traininers as well as some features of the fitness app."
              />
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
