import React from "react";
import Head from "next/head";

export default function Start() {
  return (
    <>
      <Head>
        <title>Fitt AF</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous"
        />
      </Head>

      <div class="signupBg">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-6 order-2 order-md-1">
              <h1 class="signupHeading">Let's Go</h1>
              <p>
                Fill in your details below and we'll be in touch to get you
                signed up!
              </p>
              <div>
                {/* <form action="/start" method="post">
          <label for="name">Name*</label>
          <input type="text" name="name" required />
          <label for="email">Email*</label>
          <input type="email" name="email" required />
          <label for="contactNumber">Contact Number*</label>
          <input type="tel" name="contactNumber" required />
          <label for="goal">Number one goal</label>
          <textarea name="goal" rows="2" cols="80"></textarea>
          <button type="submit" name="button" class="light grow btn">SEND</button>
        </form> */}
              </div>
            </div>

            <div class="col-md-6 order-md-2 my-auto imgDiv"></div>
          </div>
        </div>
      </div>
    </>
  );
}
